# Generated by Django 5.1.6 on 2025-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
