# Generated by Django 5.1.6 on 2025-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
