# Generated by Django 5.1.6 on 2025-02-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_remove_ride_confirmed_ride_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
