# Generated by Django 5.1.6 on 2025-02-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='liability_accepted',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
