# Generated by Django 5.1.6 on 2025-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_remove_ride_liability_accepted_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
