# Generated by Django 5.1.6 on 2025-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_remove_ride_phone_number_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='phone_number',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
