# Generated by Django 5.1.6 on 2025-02-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_ride_phone_number_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_location',
        ),
    ]
