# Generated by Django 5.1.6 on 2025-02-24 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_remove_ride_destination_remove_ride_start_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='time',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
